//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vcMiniX2.rc
//
#define IDM_ABOUTBOX                    16
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDB_PRINTER                     129
#define IDD_WIZARD                      131
#define IDB_GLOBE                       133
#define IDB_SETUP                       134
#define IDW_CONNECT                     236
#define IDW_MINIX2                      237
#define IDW_ADVANCED                    238
#define IDD_MINIX2_DLG                  329
#define IDB_AMPTEK_LOGO_SM              330
#define IDB_MINI_X_LOGO                 331
#define IDB_MINIX_HW_SM                 332
#define IDB_MINI_X                      333
#define IDI_RAD32_HV_ON                 334
#define IDI_STOPSIGN                    335
#define IDI_EXIT32                      336
#define IDI_LOCKOPEN32                  337
#define IDI_LOCKCLOSED32                338
#define IDI_RAD32                       339
#define IDB_MINI_X_50KV                 340
#define IDI_LOCKRESHORTED32             341
#define IDI_STATUS_INFO                 342
#define IDB_AMPTEK_LOGO                 343
#define IDD_MX2_CONNECT                 429
#define IDD_ADVANCED                    529
#define IDI_ADVANCED_ICON               530
#define IDB_DIALOG_WIZ                  1006
#define IDB_DIALOG_WIZ2                 1007
#define IDB_DIALOG_WIZ_MODELESS         1007
#define IDC_SHEETRECT                   1010
#define RB_ACCEPT                       1011
#define RB_DECLINE                      1012
#define ST_CAPTION                      1018
#define IDC_EDIT_DET_INFO               1023
#define IDC_STATIC_CONNECTION_STATUS    1027
#define IDC_STATUS_EDIT                 3000
#define IDC_TEMPERATURE_SENSOR_LABEL    3001
#define IDC_POWER_MW_LABEL              3002
#define IDC_TEMPERATURE_SENSOR          3003
#define IDC_SERIAL_NUMBER               3004
#define IDC_INTERLOCK_LABEL             3005
#define IDC_XRAY_ON_LABEL               3006
#define IDC_POWER_MW                    3007
#define IDC_FAULT_DISPLAY_LABEL         3008
#define IDC_MINIX2_MAIN_PANEL_LABEL     3009
#define IDC_AMPTEK_LOGO_PIC             3010
#define IDC_MINIX_LOGO_PIC              3011
#define IDC_HIGHVOLTAGECONTROLLABEL2    3014
#define IDC_HIGHVOLTAGECONTROLLABEL3    3015
#define IDC_HIGHVOLTAGECONTROLMIN       3016
#define IDC_CURRENTCONTROLMIN           3017
#define IDC_HIGHVOLTAGECONTROLMAX       3018
#define IDC_CURRENTCONTROLMAX           3019
#define IDC_HIGHVOLTAGEMONITORTEXT      3020
#define IDC_CURRENTMONITORTEXT          3021
#define IDC_HIGHVOLTAGECONTROLLABEL     3022
#define IDC_HIGHVOLTAGECONTROLLABEL4    3023
#define IDC_CURRENTCONTROLLABEL         3024
#define IDC_CURRENTCONTROLLABEL2        3025
#define IDC_HIGHVOLTAGEMONITORLABEL     3026
#define IDC_CURRENTMONITORLABEL         3027
#define IDC_OUT_OF_RANGE_LBL            3028
#define IDC_HV_ON                       3029
#define IDC_HV_OFF                      3030
#define IDC_SETHIGHVOLTAGECONTROLEDIT   3032
#define IDC_SETCURRENTCONTROLEDIT       3033
#define IDC_SETHIGHVOLTAGEANDCURRENTBUTTON 3034
#define IDC_HIGHVOLTAGEANDCURRENTGROUP  3035
#define IDC_INTERLOCK_OPEN              3036
#define IDC_INTERLOCK_CLOSED            3037
#define IDC_XRAY_ON_PIC                 3038
#define IDC_STATIC_ISO_CURVE_50KV       3039
#define IDC_INTERLOCK_SHORTED           3040
#define IDC_ADVANCED_BUTTON             3041
#define IDC_STATUS_INFO_PIC             3042
#define IDC_MINX_GROUP                  3043
#define IDC_STATIC_ISO_CURVE_50KV_4W    3050
#define IDC_STATIC_ISO_CURVE_50KV_10W   3051
#define IDC_STATIC_ISO_CURVE_70KV_10W   3052
#define IDC_HW_IMAGE_50KV_4W            3053
#define IDC_HW_IMAGE_50KV_10W           3054
#define IDC_HW_IMAGE_70KV_10W           3055
#define IDB_ISOPOWER_CURVE_50KV_4W      3300
#define IDB_ISOPOWER_CURVE_50KV_10W     3301
#define IDB_ISOPOWER_CURVE_70KV_10W     3302
#define IDB_TUBE_50KV_4W                3303
#define IDB_TUBE_50KV_10W               3304
#define IDB_TUBE_70KV_10W               3305
#define IDC_BUTTON_CLOSE_DEVICE         4049
#define IDC_BUTTON_COUNT_DEVICES        4051
#define IDC_BUTTON_FIND_USB_DEVICE      4053
#define IDC_CONNECTOK                   4063
#define IDC_EDIT_STATUS2                4070
#define IDC_RADIO_COMMTYPE2             4072
#define IDC_SPIN_SELECT_DEVICE          4075
#define IDC_STATIC_FOUND2               4077
#define IDC_STATIC_NUM_DEVICES          4089
#define IDC_STATIC_NUM_DEVICES2         4090
#define IDC_STATIC_SELECT_USB_DEVICE_LABEL 4092
#define IDC_LABEL_ON_TIME               5000
#define IDC_LABEL_WARMUP_STEP           5001
#define IDC_LABEL_ADVANCED_OPTION_STATUS_2 5002
#define IDC_LABEL_ADVANCED_OPTION_STATUS_1 5003
#define IDC_LABEL_ADVANCED_OPTION_STATUS_0 5004
#define IDC_BUTTON_MX2_ASCII_CMD_2      5005
#define IDC_BUTTON_MX2_ASCII_CMD_0      5006
#define IDC_BUTTON_MX2_ASCII_CMD_1      5007
#define IDC_GROUP_ADVANCED_OPTIONS      5008
#define IDC_BUTTON_MX2_ADVANCED_4       5009
#define IDC_BUTTON_MX2_ADVANCED_3       5010
#define IDC_BUTTON_MX2_ADVANCED_2       5011
#define IDC_BUTTON_MX2_ADVANCED_1       5012
#define IDC_BUTTON_MX2_ADVANCED_0       5013
#define IDC_BUTTON_MX2_ADVANCED_DONE    5014
#define IDC_EDIT_MX2_ADVANCED_DISPLAY   5015
#define IDC_LABEL_RUN_MONTHLY_WU        5016
#define IDC_BUTTON_WARMUP_SEQUENCE_0    5017
#define IDC_BUTTON_WARMUP_SEQUENCE_1    5018
#define IDC_BUTTON_WARMUP_SEQUENCE_2    5019
#define IDC_GROUP_WARMUP                5020
#define IDC_EDIT_MISC_DATA_MX2          5021
#define IDC_BUTTON_READ_MISC_DATA_MX2   5022
#define IDC_BUTTON_WRITE_MISC_DATA_MX2  5023
#define IDC_BUTTON_CLEAR_MISC_DATA_MX2  5024
#define IDC_GROUP_MISC_DATA_MX2         5025
#define IDC_GROUP_ADVANCED_PAGE         5026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
